# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3316392dd8a187a1c912558a2f6102aef537fbd057e2673bc8ce74bc5bf10d041a0177271711526b083ef50405b70a2a1db2d6ad20000fdeafa0db7b523474fc

test:
  secret_key_base: 561804b6c146cbb8291324cc607f374f22f9e7a50a505dc832c0bacdcdd3985df21fc7c72789fa3efd611d4d2f86e809d57320ca5aaa4de37542fcc014358f8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
